import React, { useState, useRef, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import {
  Building2, Phone, Mail, MapPin, Hash, FileImage,
  Upload, X, Save, CheckCircle, AlertCircle, Info, Shield
} from 'lucide-react';

export default function BusinessProfile({ navigateTo }) {
  const { user, updateUser } = useAuth();

  const [form, setForm] = useState({
    businessName: user?.businessName || '',
    address: user?.address || '',
    phone: user?.phone || '',
    email: user?.email || '',
    gstin: user?.gstin || '',
    sacCode: user?.sacCode || '',
    state: user?.state || '27-Maharashtra',
  });

  const [logoPreview, setLogoPreview] = useState(user?.logo || null);
  const [logoFile, setLogoFile] = useState(null);
  const [success, setSuccess] = useState('');
  const [error, setError] = useState('');
  const logoRef = useRef(null);

  useEffect(() => {
    if (user?.logo && !logoFile) {
      setLogoPreview(user.logo);
    }
  }, [user?.logo, logoFile]);

  const handleChange = (e) => {
    setForm(p => ({ ...p, [e.target.name]: e.target.value }));
    setError(''); setSuccess('');
  };

  const handleLogoChange = (e) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith('image/')) { setError('Logo must be an image file.'); return; }
    if (file.size > 2 * 1024 * 1024) { setError('Logo must be smaller than 2MB.'); return; }
    setLogoFile(file);
    const reader = new FileReader();
    reader.onload = (ev) => setLogoPreview(ev.target.result);
    reader.readAsDataURL(file);
    setError('');
  };

  const handleRemoveLogo = () => {
    setLogoFile(null);
    setLogoPreview(null);
    if (logoRef.current) logoRef.current.value = '';
  };

  const handleSave = async (e) => {
    e.preventDefault();
    if (!form.businessName.trim()) { setError('Business name is required.'); return; }

    let logoBase64 = logoPreview; // keep existing unless replaced
    if (logoFile) {
      logoBase64 = await new Promise((resolve, reject) => {
        const reader = new FileReader();
        reader.onload = ev => resolve(ev.target.result);
        reader.onerror = reject;
        reader.readAsDataURL(logoFile);
      });
    }
    if (!logoFile && logoPreview === null) {
      logoBase64 = null; // user removed logo
    }

    updateUser({ ...form, logo: logoBase64 });
    setSuccess('Business profile updated successfully!');
    setTimeout(() => setSuccess(''), 3500);
  };

  const inputCls = 'w-full bg-slate-800/60 border border-slate-700 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 outline-none rounded-xl px-4 py-2.5 text-slate-100 placeholder:text-slate-500 transition text-sm';
  const inputIconCls = 'w-full bg-slate-800/60 border border-slate-700 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 outline-none rounded-xl pl-10 pr-4 py-2.5 text-slate-100 placeholder:text-slate-500 transition text-sm';
  const labelCls = 'text-xs font-semibold text-slate-400 uppercase tracking-wide block mb-1.5';

  return (
    <div className="max-w-5xl mx-auto space-y-6 pb-16">

      {/* Info banner */}
      <div className="flex items-start gap-3 bg-blue-500/10 border border-blue-500/20 rounded-xl px-4 py-3 text-sm text-blue-300">
        <Info className="h-4 w-4 mt-0.5 shrink-0" />
        <span>These details appear on every invoice, event bill, and payslip generated by your account.</span>
      </div>

      <form onSubmit={handleSave} className="space-y-6">

        {/* Logo section */}
        <div className="glass-panel rounded-2xl border border-slate-700/50 p-6 space-y-4">
          <h2 className="text-sm font-bold text-slate-200 flex items-center gap-2">
            <FileImage className="h-4 w-4 text-indigo-400" /> Business Logo
            <span className="text-slate-500 font-normal text-xs">(optional)</span>
          </h2>
          <div className="flex items-center gap-5">
            {/* Preview */}
            <div className="w-20 h-20 rounded-xl border-2 border-dashed border-slate-600 flex items-center justify-center bg-white shrink-0 overflow-hidden">
              {logoPreview
                ? <img src={logoPreview} alt="Business logo" className="w-full h-full object-contain p-1" />
                : <Building2 className="h-8 w-8 text-slate-400" />
              }
            </div>
            <div className="flex-1 space-y-2">
              <input ref={logoRef} type="file" accept="image/*" onChange={handleLogoChange} className="hidden" id="biz-logo-upload" />
              <label
                htmlFor="biz-logo-upload"
                className="flex items-center gap-2 cursor-pointer bg-slate-800/60 hover:bg-indigo-500/10 border border-dashed border-slate-600 hover:border-indigo-500 rounded-xl px-4 py-2.5 transition text-sm text-slate-300 hover:text-indigo-300 w-fit"
              >
                <Upload className="h-4 w-4" /> Upload Logo
              </label>
              <p className="text-[11px] text-slate-500">PNG, JPG, SVG · Max 2MB · Recommended 200×200px</p>
              {logoPreview && (
                <button type="button" onClick={handleRemoveLogo}
                  className="flex items-center gap-1.5 text-xs text-rose-400 hover:text-rose-300 transition">
                  <X className="h-3.5 w-3.5" /> Remove logo
                </button>
              )}
            </div>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          {/* Business Info */}
          <div className="glass-panel rounded-2xl border border-slate-700/50 p-6 space-y-4">
            <h2 className="text-sm font-bold text-slate-200 flex items-center gap-2">
              <Building2 className="h-4 w-4 text-indigo-400" /> Business Information
            </h2>

            {/* Business Name */}
            <div>
              <label className={labelCls}>Business Name <span className="text-rose-400">*</span></label>
              <div className="relative">
                <Building2 className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                <input type="text" name="businessName" value={form.businessName} onChange={handleChange}
                  placeholder="e.g. Purvi Tours & Travels" className={inputIconCls} />
              </div>
            </div>

            {/* Address */}
            <div>
              <label className={labelCls}>Business Address</label>
              <div className="relative">
                <MapPin className="absolute left-3 top-3 h-4 w-4 text-slate-500" />
                <textarea name="address" value={form.address} onChange={handleChange} rows={2}
                  placeholder="Full address as it should appear on invoices..."
                  className="w-full bg-slate-800/60 border border-slate-700 focus:border-indigo-500 focus:ring-1 focus:ring-indigo-500/20 outline-none rounded-xl pl-10 pr-4 py-2.5 text-slate-100 placeholder:text-slate-500 transition resize-none text-sm" />
              </div>
            </div>

            {/* Phone + Email */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className={labelCls}>Phone</label>
                <div className="relative">
                  <Phone className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                  <input type="tel" name="phone" value={form.phone} onChange={handleChange}
                    placeholder="10-digit phone" className={inputIconCls} />
                </div>
              </div>
              <div>
                <label className={labelCls}>Email</label>
                <div className="relative">
                  <Mail className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                  <input type="email" name="email" value={form.email} onChange={handleChange}
                    placeholder="business@example.com" className={inputIconCls} />
                </div>
              </div>
            </div>
          </div>

          {/* Tax Info */}
          <div className="glass-panel rounded-2xl border border-slate-700/50 p-6 space-y-4">
            <h2 className="text-sm font-bold text-slate-200 flex items-center gap-2">
              <Shield className="h-4 w-4 text-emerald-400" /> Tax & Compliance
            </h2>

            <div className="grid grid-cols-1 gap-4">
              {/* GSTIN */}
              <div>
                <label className={labelCls}>GSTIN <span className="text-slate-500 font-normal normal-case">(optional)</span></label>
                <div className="relative">
                  <Hash className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                  <input type="text" name="gstin" value={form.gstin} onChange={handleChange}
                    placeholder="e.g. 27FPNPS2300C1Z1" maxLength={15}
                    className={`${inputIconCls} uppercase`} />
                </div>
                {form.gstin.length > 0 && form.gstin.length < 15 && (
                  <p className="text-xs text-amber-400 flex items-center gap-1 mt-1.5">
                    <AlertCircle className="h-3 w-3" /> GSTIN should be 15 characters
                  </p>
                )}
                {form.gstin.length === 15 && (
                  <p className="text-xs text-emerald-400 flex items-center gap-1 mt-1.5">
                    <CheckCircle className="h-3 w-3" /> Looks good!
                  </p>
                )}
              </div>

              {/* SAC + State side-by-side */}
              <div className="grid grid-cols-2 gap-4">
                {/* SAC Code */}
                <div>
                  <label className={labelCls}>SAC Code</label>
                  <div className="relative">
                    <Hash className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                    <input type="text" name="sacCode" value={form.sacCode} onChange={handleChange}
                      placeholder="998559" className={inputIconCls} />
                  </div>
                </div>

                {/* State */}
                <div>
                  <label className={labelCls}>State</label>
                  <div className="relative">
                    <MapPin className="absolute left-3 top-1/2 -translate-y-1/2 h-4 w-4 text-slate-500" />
                    <input type="text" name="state" value={form.state} onChange={handleChange}
                      placeholder="e.g. 27-Maharashtra" className={inputIconCls} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Feedback */}
        {error && (
          <div className="flex items-center gap-2 bg-rose-500/10 border border-rose-500/30 text-rose-400 rounded-xl px-4 py-3 text-sm">
            <AlertCircle className="h-4 w-4 shrink-0" /> {error}
          </div>
        )}
        {success && (
          <div className="flex items-center gap-2 bg-emerald-500/10 border border-emerald-500/30 text-emerald-400 rounded-xl px-4 py-3 text-sm">
            <CheckCircle className="h-4 w-4 shrink-0" /> {success}
          </div>
        )}

        {/* Save Button */}
        <button type="submit"
          className="w-full flex items-center justify-center gap-2 py-3 bg-gradient-to-r from-indigo-600 to-violet-600 hover:from-indigo-500 hover:to-violet-500 text-white font-bold rounded-xl shadow-xl shadow-indigo-500/20 transition text-sm">
          <Save className="h-4 w-4" /> Save Business Profile
        </button>
      </form>
    </div>
  );
}
